author: paul988
description: This plugin allows you to block any command.
main: me.paul988.blockanycommand.BlockAnyCommand
name: BlockAnyCommand
version: '1.3.1'
commands:
    bac:
      description: All commands for BlockAnyCommand.
      usage: /<command>
    baclist:
        description: All blocked commands.
        usage: /<command>
    bacupdate:
        description: Force update.
        usage: /<command>
    bacreload:
        description: Reloads the plugin.
        usage: /<command>
permissions:
    BlockAnyCommand.*:
      description: Gives access to all commands.
      children:
        BlockAnyCommand.bypass: true
        BlockAnyCommand.help: true
        BlockAnyCommand.list: true
        BlockAnyCommand.update: true
        BlockAnyCommand.update.notify: true
        BlockAnyCommand.reload: true
    BlockAnyCommand.update:
      description: Allows access to /update.
      children:
        BlockAnyCommand.update.notify: true